### ISSUE TITLE
pypi package is missing the 'management' folder

### ISSUE THREAD

**Issue by steuke** [studybuffalo/django-flexible-subscriptions#143]
Hi Joshua,

first of all, thanks for making your project available!

I was following the docs when I noticed that the `management` folder (and thus command) is missing from the distribution-files. Is this on purpose?

Best,
Stefan

**Comment by studybuffalo** [comment]
Nope, definitely not intended. I suspect I forgot to include it in the `setup.py`. I'll try and get that fixed up tonight and push out a new version. Thanks for catching that!
