### ISSUE TITLE
Small bug in transaction_list html template

### ISSUE THREAD

**Issue by mikenites** [studybuffalo/django-flexible-subscriptions#153]
Hi there, thank you for doing this project. 

I believe the transaction_list.html line 57 should say: 

`{% if transaction.subscription.plan %}{{ transaction.subscription.plan }}{% else %}No subscription plan{% endif %}`

Instead of

`{% if transaction.plan %}{{ transaction.plan }}{% else %}No subscription plan{% endif %}`

**Comment by studybuffalo** [comment]
Thanks for catching that. I'll do some digging into this, but on first glance it looks like you are probably correct.

**Comment by mikenites** [comment]
Of course -- believe it is like that in the transaction_detail template as well.

**Comment by studybuffalo** [comment]
Issue resolved and incorporated into in version 0.12.1.
