### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by AlexCernik** [studybuffalo/django-flexible-subscriptions#159]
Hello, my name is Alex. I speak Spanish and I will use the google translator to ask my questions.
When a user cancels his subscription, is he subscribed until the end of his period?
When canceling the subscription, the user continues to belong to the assigned group, is this normal?

**Comment by studybuffalo** [comment]
Hi Alex - I will try this in English & in a Google Translated Spanish (with my minimal Spanish knowledge, it seems understandable).

The basic functionality right now is to just have the subscription end at the next billing date. At that point, they won't be billed again and the account is flagged as expired. The management command should remove the user form the relevant groups at that time.

--

Hola Alex: intentaré esto en inglés y en un español traducido de Google (con mi conocimiento mínimo de español, parece comprensible).

La funcionalidad básica en este momento es que la suscripción finalice en la próxima fecha de facturación. En ese momento, no se volverán a facturar y la cuenta se marcará como vencida. El comando de administración debe eliminar al usuario de los grupos relevantes en ese momento.
